name: Flutter Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.24.5

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Setup Android sign key
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/key.jks
          echo "storeFile=key.jks" >> android/key.properties
          echo "storePassword=$STORE_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties

      - name: Build All APKs (Split by ABI)
        run: |
          flutter build apk --release --split-per-abi

      - name: Get Git commit hash
        id: git
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Rename Artifacts
        run: |
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/sachet-arm64-v8a-${{ steps.git.outputs.commit_hash }}.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/sachet-armeabi-v7a-${{ steps.git.outputs.commit_hash }}.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/sachet-x86_64-${{ steps.git.outputs.commit_hash }}.apk

      - name: Upload artifact(android-arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: sachet-android-arm64-v8a-${{ steps.git.outputs.commit_hash }}
          path: build/app/outputs/flutter-apk/sachet-arm64-v8a-${{ steps.git.outputs.commit_hash }}.apk

      - name: Upload artifact(android-armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: sachet-android-armeabi-v7a-${{ steps.git.outputs.commit_hash }}
          path: build/app/outputs/flutter-apk/sachet-armeabi-v7a-${{ steps.git.outputs.commit_hash }}.apk

      - name: Upload artifact(android-x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: sachet-android-x86_64-${{ steps.git.outputs.commit_hash }}
          path: build/app/outputs/flutter-apk/sachet-x86_64-${{ steps.git.outputs.commit_hash }}.apk

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f android/app/key.jks android/key.properties
